name: Checks

on:
  push:
  pull_request:

jobs:
  build:

    # format the matrix.extras so that they display nicely
    name: >
      test-${{ matrix.os }} -
      ${{ matrix.python-version }} -
      ${{ matrix.extras == '.' && 'none' || (matrix.extras != '.' && matrix.extras || '') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
        os: [macos-latest, ubuntu-latest, windows-latest]
        extras: [
          '.',  # only package dependencies
          # ignore the CUPY optional dep, no gpu-enabled github runner used
          '.[FFTW]'  # optional dependencies
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install fftw3 libs (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y libfftw3-dev libfftw3-double3
    - name: Install fftw3 libs (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install fftw

    - name: Install dependencies
      run: |
        # prerequisites
        python -m pip install --upgrade pip wheel
        python -m pip install -r tests/requirements.txt
        python -m pip install coverage flake8
        # install dependencies
        pip install -e "${{ matrix.extras }}"
    - name: List installed packages
      run: |
        pip freeze

    - name: Test with pytest
      run: |
        # ignore the cupy imports, as we don't have a gpu-enabled pipeline setup
        coverage run --source=qpretrieve -m pytest tests --ignore=tests/test_cupy_gpu
    - name: Lint with flake8
      run: |
        flake8 --exclude _version.py .
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
